version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - sudo apt-get install default-jdk
      - wget http://apache.mirrors.lucidnetworks.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
      - sudo tar -xzvf apache-maven-3.3.9-bin.tar.gz
      - sudo mv apache-maven-3.3.9 /usr/local/.
      - export M2_HOME=/usr/local/apache-maven-3.3.9
      - export M2=$M2_HOME/bin
      - export MAVEN_OPTS="-Xms256m -Xmx512m"
      - export PATH=$M2:$PATH
      - sudo update-alternatives --config java
      - export JAVA_HOME=/usr/lib/jvm/jdk1.7.0
      - echo $JAVA_HOME
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -PbuildDocker
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build*/**
  discard-paths: yes
