version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - sudo apt-get install default-jdk -y
      - wget http://apache.mirrors.lucidnetworks.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
      - sudo tar -xzvf apache-maven-3.3.9-bin.tar.gz
      - sudo mv apache-maven-3.3.9 /usr/local/.
      - export M2_HOME=/usr/local/apache-maven-3.3.9
      - export M2=$M2_HOME/bin
      - export MAVEN_OPTS="-Xms256m -Xmx512m"
      - export PATH=$M2:$PATH
      - sudo update-alternatives --config java
      - export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/jre
      - echo $JAVA_HOME
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - sudo apt-get update
      - apt-cache policy docker-ce
      - sudo apt-get install -y docker-ce
      - sudo service docker start
      
      
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -PbuildDocker
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build*/**
  discard-paths: yes
