version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - wget http://apache.mirrors.lucidnetworks.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
      - sudo mkdir -p /usr/local/apache-maven
      - sudo mv apache-maven-3.3.9-bin.tar.gz /usr/local/apache-maven
      - cd /usr/local/apache-maven
      - sudo tar -xzvf apache-maven-3.3.9-bin.tar.gz
      - export M2_HOME=/usr/local/apache-maven-3.3.9
      - export M2=$M2_HOME/bin
      - export MAVEN_OPTS="-Xms256m -Xmx512m"
      - export PATH=$M2:$PATH
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -PbuildDocker
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build*/**
  discard-paths: yes
